### ISSUE TITLE
Usuario y grupos 

### ISSUE THREAD

**Issue by lss11** [MicrosoftDocs/powerapps-docs.es-es#2]
no logro implementar usuario  y grupo de sharepoint 365 en poweraps desde una lista de personalizada de sharepoint

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 94785ec1-e3da-4ff2-59b6-19bd28bb8680
* Version Independent ID: 4b3e4efa-1d15-2a71-fe61-ee949c54279c
* Content: [Control Tabla de datos: referencia - PowerApps](https://docs.microsoft.com/es-es/powerapps/maker/canvas-apps/controls/control-data-table#examples)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-data-table.md](https://github.com/MicrosoftDocs/powerapps-docs.es-es/blob/live/powerapps-docs/maker/canvas-apps/controls/control-data-table.md)
* Service: **powerapps**
* GitHub Login: @jasongre
* Microsoft Alias: **jasongre**

**Comment by CeciAc** [comment]
Hola, @lss11 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
