### ISSUE TITLE
Typo on Example

### ISSUE THREAD

**Issue by Ric01** [MicrosoftDocs/powerapps-docs.es-es#4]
On the spanish versión of the examples section there is a tipo on:
"Texto (1234567;89; "# [$-fr-FR] ###, ## €"; "fr-FR")"
it should be:
"Text(1234567;89; "# [$-fr-FR] ###, ## €"; "fr-FR")"

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9f30da2a-1b9d-9d31-c59e-494314144b2f
* Version Independent ID: abe8de4e-2ed5-aedc-d2b3-a819bdf40587
* Content: [Función Text - PowerApps](https://docs.microsoft.com/es-es/powerapps/maker/canvas-apps/functions/function-text#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-text.md](https://github.com/MicrosoftDocs/powerapps-docs.es-es/blob/live/powerapps-docs/maker/canvas-apps/functions/function-text.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by CeciAc** [comment]
Hello, @Ric01
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Ric01
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/es-es/powerapps/maker/canvas-apps/functions/function-text#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
