### ISSUE TITLE
Extender integracion Dynamics 365 CE con Outlook

### ISSUE THREAD

**Issue by marcesepu** [MicrosoftDocs/powerapps-docs.es-es#5]
Quisiéramos saber si podemos extender la funcionalidad de Outlook con la integración en Dynamics 365.
Quisiéramos por ejemplo que si el cliente, usa seguimiento, o categorías sobre un e-mail, obtener esa información y poder reflejarla en Dynamics 365.

Saludos

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: cdc027b4-38ef-c89e-c244-c15fd03aff9c
* Version Independent ID: 650756a9-32b7-3acd-7bc1-20b35dd61030
* Content: [Integración con Office 365 (Common Data Service) - PowerApps](https://docs.microsoft.com/es-es/powerapps/developer/common-data-service/online-integration-office-365#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/online-integration-office-365.md](https://github.com/MicrosoftDocs/powerapps-docs.es-es/blob/live/powerapps-docs/developer/common-data-service/online-integration-office-365.md)
* Service: **powerapps**
* GitHub Login: @paulliew
* Microsoft Alias: **jdaly**

**Comment by srvbpigh** [comment]
Hello, @marcesepu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @marcesepu

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
